### ISSUE TITLE
Where can i find docs, haw configure bare-metal nodes?

### ISSUE THREAD

**Issue by qveensi** [syself/hetzner-cloud-controller-manager#15]
[qveensi](https://github.com/qveensi) [yesterday](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/330#issuecomment-1709804708)
@qveensi have you tried the ccm from Syself? https://github.com/syself/hetzner-cloud-controller-manager

I picked up their solution, but I still did not find how to add iron nodes to the cluster, ccm still looks for nodes in hcloud, not robots, and there are no instructions on how to add nodes.

i used chart syself/ccm-hetzner with all the necessary keys in secret, including the login/password for robots.

logs from ccm:
```
I0907 09:23:52.146790       1 event.go:294] "Event occurred" object="k8s-node-2" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="RemovingNode" message="Node k8s-node-2 event: Removing Node k8s-node-2 from Controller"
W0907 09:24:10.109757       1 actual_state_of_world.go:541] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="k8s-node-2" does not exist
I0907 09:24:10.124833       1 range_allocator.go:367] Set node k8s-node-2 PodCIDR to [10.3.68.0/24]
I0907 09:24:12.150695       1 event.go:294] "Event occurred" object="k8s-node-2" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="RegisteredNode" message="Node k8s-node-2 event: Registered Node k8s-node-2 in Controller"
W0907 09:24:19.007274       1 topologycache.go:199] Can't get CPU or zone information for k8s-node-2 node
W0907 09:24:46.685193       1 topologycache.go:199] Can't get CPU or zone information for k8s-node-2 node
```
and after append bare-metal nodes in my cluster, cluster-autoscaler not working yes:
```
E0907 10:19:22.011063       1 static_autoscaler.go:354] Failed to get node infos for groups: failed to check if server  exists error: failed to get servers for node k8s-node-2 error: server not found
```

maybe i can somehow set it to ignore bare-metal nodes?

I setup cluster over kubeadm with official docs: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by guettli** [comment]
@qveensi I hope you where able to get it running. I close the issue, please ask again if you have issues.
